In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/AiCi/NLP

/content/drive/MyDrive/AiCi/NLP

# Scraping

In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
page = requests.get("https://scrapsfromtheloft.com/movies/the-adam-project-transcript/")

In [3]:
page.text

'<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: \'3\',cZone: "scrapsfromtheloft.com",cType: \'managed\',cRay: \'8db2bee82d9a4b80\',cH: \'3qNdIgTQki1OV1mip7eZw49TS977YmXTYkWQ.QiD_AE-1730368277-1.2.1.1-cSkgy8iAki97nS.du11wQpq6CiZGH0H5NJY216NhWCcSipvlhRViit_FljWBVGOA\',cUPMDTk: "\\/movies\\/the-adam-project-transcript\\/?__cf_chl_tk=wgeco2iSZ1wqI7MVvall0wa9Mgp27Twj6FNOhu1OUNk-1730368277-1.0.1.1-TseZiPvxPYkYy0bTuVcdb.shUmJDGV4JEmDveO5yq14",cFPWv: \'b\',cITimeS: \'1730368277\',cTTimeMs: \'1000\',cMTimeMs: \'390000\',cTplC: 0,cTplV: 5,cTplB: \'cf\',cK: "",fa: "\\/movies\\/the-adam-project-transcript\\/?__cf_chl_f_tk=wgeco2iSZ1wqI7MVvall0wa9Mgp27Twj6FNOhu1OUNk-1730368277-1.0.1.1-TseZiPvxPYkYy0bTuVcdb.shUmJDGV4JEmDveO5yq14",md: "F.Ev5P9NWxi_pDbipVqi7ERV1kSNqtFmpWjEf2c40X8-1730368277-1.2.1.1-0rs6WOqDRU2flN2mHAzKWk4GYjqSVKTcmJ8bHR.q.akGofVMG1IX_Y5C9xrlQjJYaBmrcxL.O6_rRZzN8DB3wgkTw6UH78cqOWTw712gVdBhYowYrIYD2col22skuVFlpDmKBKWgkohciTOznP95QG6qa2z4ak1E8VRiyBW.XPOGOlnCe_a9UNFbbCg8_Pj8P2S2mdgENR.eMyY6Ad21_HT1n.MAfsGfwT9KGEAqagNUlbqCxZGAgsuxzd_b2nc_BwutEWpaV9EmhD8iuaCeIwmLHsYcpXHVHMMOe7Lw8aR9tKip7bBaPvWdGP6.1jejnFMjMTlWmIahkK_g3NrZeOfgGLcUbJVJcxJWb_H3WbMHBjLaUr8AMeOL1zLXR.oVycPpTVdBIueNiVoRUfD__K5vTxjDPsXIDL3WwBAMaAlOMth6hps4hCfiXQxrk6xS.qFXY4EAdyyA3Z9HuLi.DpJifJTfFuzZ6KMhNXwL5KaMSkiEAF6xoMKcWHKZPorQbVzibIExDAESi80nw63jzDgGl0S9zAMbIgKngdSOVnF9UEmtqp4ZK7H5MWgePBo_EieGB0j4.wWji_0wyW.inqfgRs2.pk4uYe95zGYx5Vl77nJnckBKSt7VYHoit6Jex7Gzkc.1LfrtgyKLPERJdd7ka50eRO8n8fMuy5ZtfhCjJxfvJX2WhOdOeyaJCbyrn3IrDjHf_T5MXHsVJ3dFWsveK8k1Jt.rvg0vZNUBb1pKRURDAj2zLcCZy14dLQvIPPCtwcUUyyB2Hhsb5aP94zUPNa1LjyVPBUyv6RC9aDtnVeYuCcgTRg6PXzQjipCJ1WSClsPohxL6kpbGI9V7xmMzkOqwWPu1f2GpPa8ykAT9hfbuPx4ebdVRuzfIanaEBIK0QGUnW8jCmPVj_1zHwdsr6Upc6HLmym8nZIUhuQg5lOL7shx5927tIgUKWGqJZPTW1XhI1qJZ_owYiph0F6RHUx6EvmYvfwWBQavNMjaUFx.suRo888cDiSHux1Vr9baAPs7w_TW4La.xZ5NfkoBtIPT8J51kXqj5EUmbgcDHGNq0AGicSNrcxPE_zbLLZjjBOxea7Xn6XLSrzHeAXARz_MNGKKYFnO.LGJO51BKsBCtMq4ixVOJ7D6ZyExep_rGK9T7OQG44s69Pjh71jDquWSfc5BysY6YG792N9o_mSE2v9lHCL2uQq4u87_1PksbSl2v6.9x26GluPEwSM2dJ58ayV.8luFy4tcONBkw5zvGjdgCXBqLP0MqgCCP4u7A2lHXKuFkP1yYY2ZwfdZb2iJ6N_fvnNnhlMBINIIKTAVwW8PeGtxW5QBrmqUDRHR0A2Nogh1HEGV5ecXErQiLdJayoE68Mn_EoFZ9imJO1HIZVEogxE9KRJco.xi5CjhRY_3AQ5d9ZRwVkP0CnjFj4.Dm8Jk0vxnhmsO11NkLak2KV5_Oyp8qKOmwetGltPzEAFqsNDa5emHOJRfrEnyE65XaCH9qv5lh8rJ3UVY4xqgrLtKQBIpd8ohEr6KKMrS24i2zAyHLKsKlLct6XCypVTMuMjnhxbqiiWAfzu8A8EZYyzK0uN7VqNviBVHa7i1jybZXnzs6UnwGPWVu09fOwLfr.vfZaLE.dt1oA63zu_EfAYmKSR0a9Yx83PgUNOu9MBiWtrJHOu6RbM.mDI9dq6fd3vjpThQCKewiuV8a8o7btJtkceqPkSepQaSDwcBEOwW8unhw_69M9FwvTvVQhRD.nj9Y7Mty5ku0nUx.TOLk6nfHuq8QIpDH8QLLmUfOJYuJLMmrbUJSXIu0GrdPYJJiTaXb.NZfDYNvPQE7fWoG2ZliuYX9ZwvLIdGpCsj9H0GZ85iGC.bugpKQLU8..U_k8NR1Kc3uqF812cFCkrDx.wUM6IvwtymTUgJjv_BMtube4xFDq8_IwGeIFLkaJ3N2UhaH59Bpwq6vCC3vFDUBvm1wxZVF3mEuK1xSox3NAUdJLgQtJztBp44O4vgFz3Ccdc0L.vPSFAQY3qjOC49yy5gMRKW9spVvU08FPBSuoOvdHUI2g4C2er4q35tq4O8YRaAkl09fhX5VQZCj470hJKzPIFowobV9u.iHfg.q_SQ81CnQFV633dTqpoSS_MLkQ5hC15dP0g0N77JGPOgavEIE8fy5PhTbbExs81ucrq7ciPwj6CMQUT4alncOgCcemU.zv1Wvu5PnK8sqqC.KjdhFxydKR7bM_OCbXtF87WpXQulVpVrEpZRFULW46YS7owTCfnUkjAl11daaUinGyHz0wsty3xHZ5NroFNSlTAL3WXmfgGauzJEWimA",mdrd: "89m7jv8my00LdQReqUR7ZEmYs.8BieYzvROelZMGZ8w-1730368277-1.2.1.1-tCg.stdUOKvEgasoZFMj.IJ1.0Y.or_FxJQcsYzhC6lxwUhqG5FS_O2CZR5pnigU6td.Tg_P2Jxh8mOl.e1tvDI5G2a4qY8.HC3e0mowacoFABFjqy0TkrhzmsAwyZtZ84f3Hs8YAnC_6Cu92v_VFX1h3gakb8KzOh71RnAGGCaDIedJZW6PXeNoYPi9uGNyCVy.Nu8ToGr1dz9xFtyDXicKUB1TjpRUGugesgJiDgyA5TB.hXQmobnNcJYa63uqqbxqVfvZJTIVTnwbwDkgpR6gR4rX4J17TnUBAnOjjyM.5IqlqpL.40doFiyh9gSBnfF55KsyLB5azPVlYEFKfONTyhLHuxt0amhKLMoV59fPMFqdzSU0vIGXKrwRV4IHA9_6CYn50Jv2oDPxm13WXpe9lAWHCeLBQ2pZHyI7p4kJhkeZp05vuc7qEn77tiImcUXq4i0R7lGZ8BpjNHpdQXjzVuX5Ui6_gzaqN_ZdkLz3gw.co.2uHhyzLzxdy4eGsfTgVe_lYlwJbRf0E4.vZrtSGYTuNV2eRf4JbB0Yf9Uj7oEeRsjJg9bmz_Kw94i.0mGQQ2k4zueSVHIHO8SHzRTOcpOPxT7e6_2uuDhgv7uFrGxu.yTo06scrpYWulFrtZZR71LVverAui0H7f1L2V8yheJHJUe4Ge9cTfzSORlO7cmivtwV1FUF2GEanggale2_XEye7Tzo97fYAI80gbxCHx0PgccJOVmhm3YHh4SsXvog8HThzsDSRLYUPIUp86_itNb4kjhHHxGLsh0Kb2gWbM4xYGj28hSdthkBNE0bkglyEvOaBh_0BTkBlmfy3SLJLvmM85AmU4NBOwenWSkjYeqrdwaQzr4VZwI9zdCLNUJnQznSTRWaXXYA1vz_TkZP07rU1f7lVMoGAqkFQvQZ3lFbN8imnzlyIi79wJZYgjiavaXhRyTuFaJOizzoxLlwkYpiHThMhk3UAbLF2wVYYu6y0xyusNJkyATEDI_Ln4lEXVH7KuMCrapQbHqoB5r6icimFaDx5NgzWWYu8S_djCHf_KUBA_HKYiLHW3JLPVDAj8l5wXlJc9y0auBNMJLWUiIkgxoB7sRX8bz0owdFrP.9uwGx1girsREv206mUtLAUL1tmkMsspnfEQqnUDsN70jK6sfiXAMrNhnoFcEsBybRdXS3ZN4GGhSYSqdc1nYZVR7JtkLRbjIutfhU7FKXgs2vvt.kMIF8EoGG5BAkM8UBRH1I6l0TT.u8dTPL0GJKJIQOmJP99fTjxDFW7PjxXAYG33g6Y43BmDnDkNE26vge9acwxHp8.LnnkQlpu9XxWdOkDarHVUBxXY8S7Hlskreo3hWyQnkjscX29rOwkjJRtW6CFot_jeeaCbrQjJd1V_008dqj_i_WTrw0DXqtfDO6PKfXlpdOC0AptjC.dfD_zNJVoav2yyhyftTX72M2xROGisGdlTIAjU.dI3JYRmvPxbXqM3k_vunYGgFW6o1ZI4V6BzgR_F5fRWOmOKDvtwqhQc0_Ba6Is.LdDqYXBp37GBaekzoT_mBAqbC0DtBM9wsmktSuuj89ywQ8u4H0ydRwiOprTdMPfFn5lt6rtmItplrpyQeZi3adoALMcs8BCxdLsgTTMgvRj1MXfSjIYTXhTzyy0Nfcgdzv5rgPdHDltLYuG44YUsRHN6Z5l0XVzjLJr4tZW9bYy0vsKcCVzRboXOf3h0i2Xorn7CUXwzC8QZ9Qt99xrbvgZfehqb2nkmH7hJ3DJeestkwlciMVJ7nuhpgdraJIqBaCvklMzuCMv8wFdQI7AY2K_USelnO.EaTZIjlXo1Y58wig_KOAU7dLtIlaqfmaHystfmiOrPb8ZIy11F7uoCENnqEOHoBgjDrN5Jxghaq_WinOVj.VWSmuFdItRli2KekE_8mQo0v0uUkETrkyCEzYsG9KTysxYC.RUo20wB4UFdzsnmzZBFQWOUvGWkLwT71Fx_Ja3jgZIH5YuJ_DKmRC8HDtuftgBi8zZKYpEnbyr9jmZGJSodeJ4EyHDY19MiztZkW9aMraAIM2THUbDHsrxE6.vO_treyzInZteySRkdli.Xz8IY3DbhoNPK4IXuPa1.UEqNEY5HZ1_ZCuqUW4Zq2.gDmqqch2FoLF8r.2o8iz6uwio_0P3cwz3guG28kzOf1lSGcTeoEnivz4SeWcAVNM7DuQu9hWKlljhTAnqhtsnkwG3kJmmRGk8zvO1Z0kI5QD4Zl1i1D65OrqO3xL7A"};var cpo = document.createElement(\'script\');cpo.src = \'/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8db2bee82d9a4b80\';window._cf_chl_opt.cOgUHash = location.hash === \'\' && location.href.indexOf(\'#\') !== -1 ? \'#\' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === \'\' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf(\'?\') !== -1 ? \'?\' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\\/movies\\/the-adam-project-transcript\\/?__cf_chl_rt_tk=wgeco2iSZ1wqI7MVvall0wa9Mgp27Twj6FNOhu1OUNk-1730368277-1.0.1.1-TseZiPvxPYkYy0bTuVcdb.shUmJDGV4JEmDveO5yq14" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName(\'head\')[0].appendChild(cpo);}());</script></body></html>'

In [4]:
soup = BeautifulSoup(page.text, 'lxml')

In [5]:
soup.find_all("div",class_="elementor-widget-theme-post-content")

[]

In [6]:
for p in soup.find_all("div",class_="elementor-widget-theme-post-content"):
  print(p.text)

### Scrape from multiple link

In [7]:
def url_to_transcript(url):
    page = requests.get(url).text
    soup = BeautifulSoup(page, 'lxml')
    text = [p.text for p in soup.find_all('div', class_="elementor-widget-theme-post-content")]
    print(url)
    return text

In [8]:
# URLs of transcripts in scope
urls = ['https://scrapsfromtheloft.com/movies/spider-man-no-way-home-transcript/',
         'https://scrapsfromtheloft.com/movies/eternals-2021-transcript/',
         'https://scrapsfromtheloft.com/movies/wonder-woman-1984-transcript/',
         'https://scrapsfromtheloft.com/movies/joker-how-about-another-joke-murray-transcript/',
         'https://scrapsfromtheloft.com/movies/zack-snyders-justice-league-transcript/',
         'https://scrapsfromtheloft.com/comedy/shang-chi-legend-of-ten-rings-transcript/',
         'https://scrapsfromtheloft.com/comedy/venom-let-there-be-carnage-transcript/',
         'https://scrapsfromtheloft.com/movies/black-widow-2021-transcript/']

In [9]:
transcripts = [url_to_transcript(u) for u in urls]

https://scrapsfromtheloft.com/movies/spider-man-no-way-home-transcript/
https://scrapsfromtheloft.com/movies/eternals-2021-transcript/
https://scrapsfromtheloft.com/movies/wonder-woman-1984-transcript/
https://scrapsfromtheloft.com/movies/joker-how-about-another-joke-murray-transcript/
https://scrapsfromtheloft.com/movies/zack-snyders-justice-league-transcript/
https://scrapsfromtheloft.com/comedy/shang-chi-legend-of-ten-rings-transcript/
https://scrapsfromtheloft.com/comedy/venom-let-there-be-carnage-transcript/
https://scrapsfromtheloft.com/movies/black-widow-2021-transcript/

In [10]:
transcripts

[[], [], [], [], [], [], [], []]

In [11]:
import pickle

In [12]:
!mkdir transcripts

In [13]:
# Movie names
movies = ['spiderman', 'eternals', 'wonderwoman', 'joker', 'justiceleague', 'shangchi', 'venom', 'blackwidow']

In [14]:
for i,c in enumerate(movies):
  with open("transcripts/"+c+".txt","wb") as file:
    pickle.dump(transcripts[i], file)

# Cleaning

In [ ]:
import pickle

In [ ]:
# Movie names
movies = ['spiderman', 'eternals', 'wonderwoman', 'joker', 'justiceleague', 'shangchi', 'venom', 'blackwidow']

In [ ]:
data = {}
for i,c in enumerate(movies):
  with open("transcripts/"+c+".txt","rb") as file:
    data[c] = pickle.load(file)

In [ ]:
data.keys()

dict_keys(['spiderman', 'eternals', 'wonderwoman', 'joker', 'justiceleague', 'shangchi', 'venom', 'blackwidow'])

In [ ]:
data.values()

### Cleaning the data

In [ ]:
# We are going to change this to key: movies, value: string format
def combine_text(list_of_text):
    '''Takes a list of text and combines them into one large chunk of text.'''
    combined_text = ' '.join(list_of_text)
    return combined_text

In [ ]:
# Combine it!
data_combined = {key: [combine_text(value)] for (key, value) in data.items()}

In [ ]:
data_combined

In [ ]:
# We can either keep it in dictionary format or put it into a pandas dataframe
import pandas as pd
pd.set_option('max_colwidth',150)

data_df = pd.DataFrame.from_dict(data_combined).transpose()
data_df.columns = ['transcript']
data_df = data_df.sort_index()
data_df

                                                                                                                                                          transcript
blackwidow       Following the events of Captain America: Civil War (2016), Natasha Romanoff finds herself on the run and forced to confront a dangerous conspira...
eternals         The saga of the Eternals, a race of immortal beings who lived on Earth and shaped its history and civilizations.  * * * It is time. (SOFT DRAMAT...
joker            CLASSIC SCENE Arthur is invited to appear on Murray’s show due to the popularity of his stand-up routine clips. Before the show goes live, Arthu...
justiceleague    Determined to ensure Superman’s ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of ...
shangchi         Shang-Chi is a young man who is in denial about his vocation and his magnificent warrior destiny; he lives in San Francisco, calls himself “Shau...
spiderman        Peter Parker’s secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that ...
venom            In 1996, a young Cletus Kasady watches helplessly as his love, Frances Barrison, is taken away from St. Estes Home for Unwanted Children to the ...
wonderwoman      As a young girl, Diana Prince participates in a multi-stage athletic competition on Themyscira against older Amazons. After falling from her hor...

In [ ]:
data_df.transcript.loc['spiderman']

In [ ]:
import re
import string

def clean_text_round1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', ' ', text)
    text = re.sub('\(.*?\)', ' ', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = re.sub('\w*\d\w*', ' ', text)
    return text

In [ ]:
round1 = lambda x: clean_text_round1(x)

In [ ]:
data_clean = pd.DataFrame(data_df.transcript.apply(round1))
data_clean

                                                                                                                                                          transcript
blackwidow       following the events of captain america  civil war    natasha romanoff finds herself on the run and forced to confront a dangerous conspiracy wi...
eternals         the saga of the eternals  a race of immortal beings who lived on earth and shaped its history and civilizations         it is time    it’s beaut...
joker            classic scene arthur is invited to appear on murray’s show due to the popularity of his stand up routine clips  before the show goes live  arthu...
justiceleague    determined to ensure superman’s ultimate sacrifice was not in vain  bruce wayne aligns forces with diana prince with plans to recruit a team of ...
shangchi         shang chi is a young man who is in denial about his vocation and his magnificent warrior destiny  he lives in san francisco  calls himself “shau...
spiderman        peter parker’s secret identity is revealed to the entire world  desperate for help  peter turns to doctor strange to make the world forget that ...
venom            in    a young cletus kasady watches helplessly as his love  frances barrison  is taken away from st  estes home for unwanted children to the rav...
wonderwoman      as a young girl  diana prince participates in a multi stage athletic competition on themyscira against older amazons  after falling from her hor...

In [ ]:
# Apply a second round of cleaning
def clean_text_round2(text):
    '''Get rid of some additional punctuation and non-sensical text that was missed the first time around.'''
    text = re.sub('[‘’“”…♪♪]', '', text)
    text = re.sub('\n', ' ', text)
    text = re.sub('\xa0', ' ', text)
    return text

round2 = lambda x: clean_text_round2(x)

In [ ]:
# Let's take a look at the updated text
data_clean = pd.DataFrame(data_clean.transcript.apply(round2))
data_clean

                                                                                                                                                          transcript
blackwidow       following the events of captain america  civil war    natasha romanoff finds herself on the run and forced to confront a dangerous conspiracy wi...
eternals         the saga of the eternals  a race of immortal beings who lived on earth and shaped its history and civilizations         it is time    its beauti...
joker            classic scene arthur is invited to appear on murrays show due to the popularity of his stand up routine clips  before the show goes live  arthur...
justiceleague    determined to ensure supermans ultimate sacrifice was not in vain  bruce wayne aligns forces with diana prince with plans to recruit a team of m...
shangchi         shang chi is a young man who is in denial about his vocation and his magnificent warrior destiny  he lives in san francisco  calls himself shaun...
spiderman        peter parkers secret identity is revealed to the entire world  desperate for help  peter turns to doctor strange to make the world forget that h...
venom            in    a young cletus kasady watches helplessly as his love  frances barrison  is taken away from st  estes home for unwanted children to the rav...
wonderwoman      as a young girl  diana prince participates in a multi stage athletic competition on themyscira against older amazons  after falling from her hor...

## Organizing Data

In [ ]:
data_clean = data_clean.sort_index()
data_clean

                                                                                                                                                          transcript
blackwidow       following the events of captain america  civil war    natasha romanoff finds herself on the run and forced to confront a dangerous conspiracy wi...
eternals         the saga of the eternals  a race of immortal beings who lived on earth and shaped its history and civilizations         it is time    its beauti...
joker            classic scene arthur is invited to appear on murrays show due to the popularity of his stand up routine clips  before the show goes live  arthur...
justiceleague    determined to ensure supermans ultimate sacrifice was not in vain  bruce wayne aligns forces with diana prince with plans to recruit a team of m...
shangchi         shang chi is a young man who is in denial about his vocation and his magnificent warrior destiny  he lives in san francisco  calls himself shaun...
spiderman        peter parkers secret identity is revealed to the entire world  desperate for help  peter turns to doctor strange to make the world forget that h...
venom            in    a young cletus kasady watches helplessly as his love  frances barrison  is taken away from st  estes home for unwanted children to the rav...
wonderwoman      as a young girl  diana prince participates in a multi stage athletic competition on themyscira against older amazons  after falling from her hor...

In [ ]:
full_names = ['Black Widow', 'Eternals', 'Joker', 'Justice League (Jack Snyder)',
              'Shang Chi and the Legend of the Ten Rings', 'Spider-man: No Way Home', 'Venom: Let There be Carnage', 'Wonder Woman' ]
data_clean['full_name'] = full_names
data_clean

,transcript,full_name
blackwidow,following the events of captain america civil war natasha romanoff finds herself on the run and forced to confront a dangerous conspiracy wi...,Black Widow
eternals,the saga of the eternals a race of immortal beings who lived on earth and shaped its history and civilizations it is time its beauti...,Eternals
joker,classic scene arthur is invited to appear on murrays show due to the popularity of his stand up routine clips before the show goes live arthur...,Joker
justiceleague,determined to ensure supermans ultimate sacrifice was not in vain bruce wayne aligns forces with diana prince with plans to recruit a team of m...,Justice League (Jack Snyder)
shangchi,shang chi is a young man who is in denial about his vocation and his magnificent warrior destiny he lives in san francisco calls himself shaun...,Shang Chi and the Legend of the Ten Rings
spiderman,peter parkers secret identity is revealed to the entire world desperate for help peter turns to doctor strange to make the world forget that h...,Spider-man: No Way Home
venom,in a young cletus kasady watches helplessly as his love frances barrison is taken away from st estes home for unwanted children to the rav...,Venom: Let There be Carnage
wonderwoman,as a young girl diana prince participates in a multi stage athletic competition on themyscira against older amazons after falling from her hor...,Wonder Woman

In [ ]:
data_clean.to_pickle("corpus_clean.pkl")

In [ ]:
data_df.to_pickle("corpus.pkl")

### Document-Term Matrix

In [ ]:
# We are going to create a document-term matrix using CountVectorizer, and exclude common English stop words
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(data_clean.transcript)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names_out())
data_dtm.index = data_clean.index
data_dtm

,aah,abandon,abandoned,abandons,abducted,abductions,abilities,ability,able,aboard,...,youve,yup,zap,zero,zeroes,zeus,zhong,zones,zoologist,zoom
blackwidow,0,0,3,0,0,0,0,0,3,0,...,3,2,0,1,0,0,0,1,0,0
eternals,1,0,1,0,0,0,0,0,4,0,...,13,0,0,0,0,0,0,0,0,0
joker,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
justiceleague,0,1,3,0,1,2,2,0,4,1,...,5,0,0,1,1,1,0,0,0,1
shangchi,0,0,0,0,0,0,0,0,2,0,...,4,0,0,0,0,0,0,0,0,0
spiderman,0,0,0,0,0,0,0,1,2,0,...,4,2,1,1,0,0,0,0,0,0
venom,1,0,0,0,0,0,0,1,3,0,...,0,0,0,1,0,0,0,0,0,0
wonderwoman,0,0,0,0,0,0,0,0,3,1,...,6,0,0,0,0,0,2,0,1,0

In [ ]:
data_dtm.to_pickle("dtm.pkl")

In [ ]:
# Let's also pickle the cleaned data (before we put it in document-term matrix format) and the CountVectorizer object
data_clean.to_pickle('data_clean.pkl')
pickle.dump(cv, open("cv.pkl", "wb"))