1.	Buatlah 2 algoritma ensemble learning:  
        a.	Gunakan simple technique untuk kasus regresi menggunakan diabetes load_diabetes dataset dari sklearn. Kemudian carilah nilai RMSE, MAE, dan MAPE dari performa model ensemble learningnya.  
        b.	Gunakan advanced technique untuk melakukan klasifikasi pada dataset iris dari library sklearn. Kemudian buatlah dan tampilkan confusion matrix dari final modelnya  
        
        Notes: Bebas memilih menggunakan teknik ensemble learning manapun dan algotima manapun sebagai base dan final modelnya.

2. Lakukanlah 5-fold cross validation pada salah satu base model yang digunakan pada nomor 1.b

In [3]:
# Load diabetes dataset

from sklearn.datasets import load_diabetes

diabetes = load_diabetes(as_frame=True)
diabetes = diabetes.frame
diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
...

In [ ]:
...

In [4]:
# Load iris dataset

from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
iris = iris.frame
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
...